# Site information
title: RISCV Multi Cycle
description: > 
    A simple multi-cycle, area optimised implementation of the RISCV
    instruction set architecture.

baseurl: "/riscv-multi-cycle" 
github_username:  ben-marshall

# Build settings
markdown: kramdown
